import { AIModel } from '@/types'

export const AI_MODELS: AIModel[] = [
  {
    id: 'claude',
    name: 'Claude',
    provider: 'Anthropic',
    currentModel: 'claude-sonnet-4-6',
    status: 'active',
    badge: 'premium',
    color: '#7C3AED',
    bgColor: 'bg-purple-950/40',
    borderColor: 'border-purple-500/30',
    qualityScore: 96,
    speedScore: 72,
    costScore: 30,
    useCases: ['Stratégie', 'Architecture', 'Code', 'Raisonnement', 'Validation'],
    monthlyBudget: 20,
    usedBudget: 8.40,
    description: 'Raisonnement avancé, code complexe et stratégie',
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    provider: 'OpenAI',
    currentModel: 'GPT-4o',
    status: 'active',
    badge: 'creative',
    color: '#10A37F',
    bgColor: 'bg-emerald-950/40',
    borderColor: 'border-emerald-500/30',
    qualityScore: 92,
    speedScore: 85,
    costScore: 35,
    useCases: ['Image', 'Vidéo', 'Multimodal', 'Créatif', 'Marketing', 'Maquettes'],
    monthlyBudget: 20,
    usedBudget: 6.20,
    description: 'Génération visuelle, créativité et multimodal',
  },
  {
    id: 'ollama',
    name: 'Ollama Local',
    provider: 'Local — Mac M3',
    currentModel: 'llama3.2:3b',
    status: 'active',
    badge: 'local',
    color: '#F59E0B',
    bgColor: 'bg-amber-950/40',
    borderColor: 'border-amber-500/30',
    qualityScore: 65,
    speedScore: 90,
    costScore: 100,
    useCases: ['Brouillons', 'Résumés', 'Hashtags', 'Reformulations', 'Tâches simples'],
    description: '100% local, gratuit, pour tâches légères',
  },
  {
    id: 'future',
    name: 'Futures IAs',
    provider: 'À connecter',
    currentModel: '—',
    status: 'inactive',
    badge: 'future',
    color: '#6B7280',
    bgColor: 'bg-gray-900/40',
    borderColor: 'border-gray-600/30',
    qualityScore: 0,
    speedScore: 0,
    costScore: 0,
    useCases: ['Gemini', 'Mistral', 'Groq', 'OpenAI API', 'GPU Serveur'],
    description: 'Gemini, Mistral, Groq, serveur GPU…',
  },
]
