import { Task } from '@/types'

export const TASKS: Task[] = [
  {
    id: 'architecture',
    label: 'Architecture projet',
    category: 'strategy',
    recommendedAI: 'claude',
    fallbackAI: 'ollama',
    reason: 'Raisonnement structuré et vision long terme',
    quality: 5, speed: 3, cost: '$$$', risk: 'low',
    estimatedTokens: 4000,
  },
  {
    id: 'code-complex',
    label: 'Code complexe',
    category: 'code',
    recommendedAI: 'claude',
    fallbackAI: 'ollama',
    reason: 'Claude Code excelle sur les systèmes complexes',
    quality: 5, speed: 3, cost: '$$$', risk: 'low',
    estimatedTokens: 6000,
  },
  {
    id: 'code-simple',
    label: 'Code simple / snippet',
    category: 'code',
    recommendedAI: 'ollama',
    fallbackAI: 'claude',
    reason: 'Ollama suffit pour les tâches répétitives',
    quality: 3, speed: 5, cost: 'FREE', risk: 'low',
    estimatedTokens: 800,
  },
  {
    id: 'image',
    label: 'Génération image',
    category: 'image',
    recommendedAI: 'chatgpt',
    fallbackAI: 'future',
    reason: 'DALL-E 3 / GPT-4o Vision natif',
    quality: 5, speed: 4, cost: '$$', risk: 'low',
    estimatedTokens: 500,
  },
  {
    id: 'video',
    label: 'Génération vidéo',
    category: 'video',
    recommendedAI: 'chatgpt',
    fallbackAI: 'future',
    reason: 'Sora ou outil vidéo via ChatGPT',
    quality: 5, speed: 2, cost: '$$$$', risk: 'medium',
    estimatedTokens: 1000,
  },
  {
    id: 'summary',
    label: 'Résumé article',
    category: 'writing',
    recommendedAI: 'ollama',
    fallbackAI: 'claude',
    reason: 'Tâche simple, économise les tokens Claude',
    quality: 3, speed: 5, cost: 'FREE', risk: 'low',
    estimatedTokens: 1200,
  },
  {
    id: 'hashtags',
    label: 'Hashtags réseaux sociaux',
    category: 'writing',
    recommendedAI: 'ollama',
    fallbackAI: 'claude',
    reason: 'Tâche légère, gratuit en local',
    quality: 3, speed: 5, cost: 'FREE', risk: 'low',
    estimatedTokens: 300,
  },
  {
    id: 'post-variants',
    label: 'Variantes de posts',
    category: 'writing',
    recommendedAI: 'ollama',
    fallbackAI: 'chatgpt',
    reason: 'Volume élevé, priorité économie',
    quality: 3, speed: 5, cost: 'FREE', risk: 'low',
    estimatedTokens: 600,
  },
  {
    id: 'marketing-strategy',
    label: 'Stratégie marketing',
    category: 'strategy',
    recommendedAI: 'claude',
    fallbackAI: 'ollama',
    reason: 'Analyse profonde et cohérence stratégique',
    quality: 5, speed: 3, cost: '$$$', risk: 'low',
    estimatedTokens: 5000,
  },
  {
    id: 'ui-mockup',
    label: 'Maquette UI',
    category: 'design',
    recommendedAI: 'chatgpt',
    fallbackAI: 'claude',
    reason: 'ChatGPT pour le visuel, Claude Code pour l\'implémentation',
    quality: 5, speed: 3, cost: '$$$$', risk: 'medium',
    estimatedTokens: 3000,
  },
  {
    id: 'seo',
    label: 'Optimisation SEO',
    category: 'seo',
    recommendedAI: 'claude',
    fallbackAI: 'chatgpt',
    reason: 'Analyse sémantique et structure editoriale',
    quality: 5, speed: 3, cost: '$$$', risk: 'low',
    estimatedTokens: 2500,
  },
  {
    id: 'google-ads',
    label: 'Google Ads — copies',
    category: 'ads',
    recommendedAI: 'claude',
    fallbackAI: 'chatgpt',
    reason: 'Raisonnement persuasif et contraintes de format',
    quality: 5, speed: 3, cost: '$$$', risk: 'low',
    estimatedTokens: 2000,
  },
  {
    id: 'meta-ads',
    label: 'Meta Ads — visuels + copies',
    category: 'ads',
    recommendedAI: 'chatgpt',
    fallbackAI: 'claude',
    reason: 'ChatGPT pour les visuels, Claude pour les copies',
    quality: 5, speed: 3, cost: '$$$', risk: 'low',
    estimatedTokens: 2500,
  },
  {
    id: 'automation',
    label: 'Publication automatique n8n',
    category: 'automation',
    recommendedAI: 'claude',
    fallbackAI: 'ollama',
    reason: 'Claude Code génère les workflows n8n',
    quality: 5, speed: 3, cost: '$$$', risk: 'medium',
    estimatedTokens: 4500,
  },
  {
    id: 'validation',
    label: 'Validation finale',
    category: 'validation',
    recommendedAI: 'claude',
    fallbackAI: 'chatgpt',
    reason: 'Toujours valider avec Claude pour la cohérence',
    quality: 5, speed: 3, cost: '$$$', risk: 'low',
    estimatedTokens: 2000,
  },
]
