import { WorkSession } from '@/types'

export const WORK_SESSIONS: WorkSession[] = [
  {
    id: 'ws-001',
    date: '2026-05-19',
    mission: 'Stratégie contenu LinkedIn Q3 2026',
    project: 'AI Command Center',
    status: 'completed',
    aiSequence: ['ollama', 'claude', 'chatgpt'],
    steps: [
      {
        id: 's1',
        ai: 'ollama',
        action: 'Brouillon initial',
        promptSummary: 'Génère 10 idées de posts LinkedIn B2B sur l\'IA',
        outputSummary: '10 idées thématiques avec angles différenciants',
        timestamp: '09:12',
        tokensUsed: 850,
        status: 'completed',
      },
      {
        id: 's2',
        ai: 'claude',
        action: 'Stratégie éditoriale',
        promptSummary: 'Transforme ces idées en calendrier éditorial trimestriel avec KPIs',
        outputSummary: 'Calendrier 13 semaines, 3 posts/sem, KPIs définis',
        timestamp: '09:28',
        tokensUsed: 3200,
        status: 'completed',
      },
      {
        id: 's3',
        ai: 'chatgpt',
        action: 'Visuels bannières',
        promptSummary: 'Crée 3 templates visuels LinkedIn corporate violet/blanc',
        outputSummary: '3 bannières PNG 1200×628 générées',
        timestamp: '09:45',
        tokensUsed: 400,
        status: 'completed',
      },
    ],
    summary: 'Calendrier éditorial Q3 complet avec 39 posts planifiés et 3 templates visuels.',
    nextAction: 'Intégrer dans n8n pour publication automatique',
    tokensUsed: 4450,
    estimatedCost: 0.18,
    savings: 0.34,
  },
  {
    id: 'ws-002',
    date: '2026-05-19',
    mission: 'Développement composant Dashboard',
    project: 'AI Command Center',
    status: 'active',
    aiSequence: ['claude'],
    steps: [
      {
        id: 's1',
        ai: 'claude',
        action: 'Architecture composants',
        promptSummary: 'Propose l\'architecture React pour le dashboard AI Command Center',
        outputSummary: 'Structure complète : 7 pages, 20+ composants, types TypeScript',
        timestamp: '14:30',
        tokensUsed: 5800,
        status: 'completed',
      },
      {
        id: 's2',
        ai: 'claude',
        action: 'Développement en cours',
        promptSummary: 'Code les composants fondations Sprint 1',
        outputSummary: 'En cours…',
        timestamp: '14:55',
        tokensUsed: 0,
        status: 'in_progress',
      },
    ],
    summary: 'Architecture définie, développement Sprint 1 en cours.',
    nextAction: 'Terminer layout + mock data, démarrer Sprint 2',
    tokensUsed: 5800,
    estimatedCost: 0.52,
    savings: 0.00,
  },
  {
    id: 'ws-003',
    date: '2026-05-18',
    mission: 'Rédaction 5 articles SEO sur l\'IA générative',
    project: 'Blog Agence',
    status: 'paused',
    aiSequence: ['ollama', 'claude'],
    steps: [
      {
        id: 's1',
        ai: 'ollama',
        action: 'Brouillons articles',
        promptSummary: 'Rédige 5 brouillons d\'articles 800 mots sur l\'IA générative',
        outputSummary: '5 brouillons structurés avec H1/H2/H3',
        timestamp: '16:00',
        tokensUsed: 12000,
        status: 'completed',
      },
      {
        id: 's2',
        ai: 'claude',
        action: 'Optimisation SEO',
        promptSummary: 'Optimise les 3 premiers articles pour les mots-clés cibles',
        outputSummary: '3 articles optimisés, score SEO estimé 85+',
        timestamp: '16:45',
        tokensUsed: 8500,
        status: 'completed',
      },
    ],
    summary: '3 articles SEO finalisés sur 5. Articles 4 et 5 en attente.',
    nextAction: 'Reprendre avec Claude pour optimiser articles 4 et 5',
    tokensUsed: 20500,
    estimatedCost: 0.38,
    savings: 1.20,
  },
  {
    id: 'ws-004',
    date: '2026-05-17',
    mission: 'Campagne Meta Ads — Lancement produit SaaS',
    project: 'Client E-commerce',
    status: 'completed',
    aiSequence: ['chatgpt', 'claude', 'chatgpt'],
    steps: [
      {
        id: 's1',
        ai: 'chatgpt',
        action: 'Visuels pub',
        promptSummary: 'Génère 6 visuels Meta Ads 1080×1080 produit SaaS moderne',
        outputSummary: '6 visuels avec CTA, couleurs brand',
        timestamp: '10:00',
        tokensUsed: 800,
        status: 'completed',
      },
      {
        id: 's2',
        ai: 'claude',
        action: 'Copies publicitaires',
        promptSummary: 'Rédige 3 versions de copies Ad pour chaque visuel (court/moyen/long)',
        outputSummary: '18 copies testables avec A/B structure',
        timestamp: '10:30',
        tokensUsed: 4200,
        status: 'completed',
      },
      {
        id: 's3',
        ai: 'chatgpt',
        action: 'Assets vidéo',
        promptSummary: 'Crée un motion graphics 15s à partir des visuels statiques',
        outputSummary: 'Vidéo 15s exportée en MP4',
        timestamp: '11:00',
        tokensUsed: 600,
        status: 'completed',
      },
    ],
    summary: 'Campagne complète : 6 visuels, 18 copies, 1 vidéo 15s. Prête pour mise en ligne.',
    nextAction: 'Mettre en ligne via n8n + monitorer les CTR',
    tokensUsed: 5600,
    estimatedCost: 0.42,
    savings: 0.58,
  },
  {
    id: 'ws-005',
    date: '2026-05-16',
    mission: 'Génération 200 hashtags Instagram nichés',
    project: 'Client Fitness',
    status: 'completed',
    aiSequence: ['ollama'],
    steps: [
      {
        id: 's1',
        ai: 'ollama',
        action: 'Génération hashtags',
        promptSummary: 'Génère 200 hashtags Instagram pour une marque fitness premium',
        outputSummary: '200 hashtags classifiés par volume et niche',
        timestamp: '08:30',
        tokensUsed: 1800,
        status: 'completed',
      },
    ],
    summary: '200 hashtags organisés en 10 groupes thématiques. 100% Ollama = 0€.',
    nextAction: 'Intégré dans le calendrier contenu',
    tokensUsed: 1800,
    estimatedCost: 0.00,
    savings: 0.16,
  },
]
