import type { AIProvider, AIProviderId, AIProviderStatus } from './types'

export const AI_PROVIDERS: AIProvider[] = [
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    shortName: 'Claude',
    category: 'text',
    status: 'active',
    envVars: ['ANTHROPIC_API_KEY'],
    capabilities: ['strategy', 'copywriting', 'quality_review', 'vision_analysis', 'data_analysis'],
    defaultModel: 'claude-sonnet-4-6',
    fallbackModel: 'claude-haiku-4-5',
    consoleUrl: 'https://console.anthropic.com/settings/keys',
    bestFor: ['stratégie premium', 'supervision qualité', 'analyse client', 'prompts complexes'],
    limits: ['coût plus élevé que les modèles economy', 'dépend de la clé Anthropic'],
    models: [
      {
        id: 'claude-sonnet-4-6',
        label: 'Claude Sonnet 4.6',
        quality: 'premium',
        speed: 'medium',
        estimatedInputCostPer1M: 3,
        estimatedOutputCostPer1M: 15,
        notes: 'Modèle principal pour stratégie, captions et supervision.',
      },
      {
        id: 'claude-haiku-4-5',
        label: 'Claude Haiku 4.5',
        quality: 'economy',
        speed: 'fast',
        estimatedInputCostPer1M: 1,
        estimatedOutputCostPer1M: 5,
        notes: 'Fallback rapide pour variantes ou brouillons simples.',
      },
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    shortName: 'OpenAI',
    category: 'image',
    status: 'active',
    envVars: ['OPENAI_API_KEY'],
    capabilities: ['copywriting', 'image_generation', 'image_editing', 'vision_analysis', 'data_analysis'],
    defaultModel: process.env.OPENAI_IMAGE_MODEL || 'gpt-image-1',
    fallbackModel: 'gpt-4o-mini',
    consoleUrl: 'https://platform.openai.com/api-keys',
    bestFor: ['génération image', 'édition image', 'fallback texte', 'outils multimodaux'],
    limits: ['billing requis', 'hard limit bloque immédiatement les images'],
    models: [
      {
        id: 'gpt-image-1',
        label: 'GPT Image 1',
        quality: 'premium',
        speed: 'medium',
        estimatedUnitCost: 0.04,
        notes: 'Image principale pour posts Facebook/Instagram.',
      },
      {
        id: 'gpt-4o-mini',
        label: 'GPT-4o mini',
        quality: 'economy',
        speed: 'fast',
        estimatedInputCostPer1M: 0.15,
        estimatedOutputCostPer1M: 0.6,
        notes: 'Fallback low-cost pour textes courts et transformations simples.',
      },
    ],
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    shortName: 'Gemini',
    category: 'text',
    status: 'planned',
    envVars: ['GEMINI_API_KEY'],
    capabilities: ['strategy', 'copywriting', 'vision_analysis', 'data_analysis', 'document_summary'],
    defaultModel: 'gemini-2.5-pro',
    fallbackModel: 'gemini-2.5-flash',
    consoleUrl: 'https://aistudio.google.com/app/apikey',
    bestFor: ['contexte long', 'documents client', 'analyse multimodale'],
    limits: ['pas encore branché dans les agents runtime'],
    models: [
      { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro', quality: 'premium', speed: 'medium' },
      { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash', quality: 'economy', speed: 'fast' },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    shortName: 'Mistral',
    category: 'text',
    status: 'planned',
    envVars: ['MISTRAL_API_KEY'],
    capabilities: ['copywriting', 'low_cost_draft', 'document_summary'],
    defaultModel: 'mistral-large-latest',
    fallbackModel: 'mistral-small-latest',
    consoleUrl: 'https://console.mistral.ai/api-keys',
    bestFor: ['drafts en français', 'coût maîtrisé', 'option européenne'],
    limits: ['moins adapté aux validations critiques que Claude pour Maestro'],
    models: [
      { id: 'mistral-large-latest', label: 'Mistral Large', quality: 'standard', speed: 'medium' },
      { id: 'mistral-small-latest', label: 'Mistral Small', quality: 'economy', speed: 'fast' },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    shortName: 'Groq',
    category: 'text',
    status: 'planned',
    envVars: ['GROQ_API_KEY'],
    capabilities: ['copywriting', 'low_cost_draft'],
    defaultModel: 'llama-3.3-70b-versatile',
    fallbackModel: 'llama-3.1-8b-instant',
    consoleUrl: 'https://console.groq.com/keys',
    bestFor: ['drafts rapides', 'variantes de captions', 'prévisualisations low-cost'],
    limits: ['à éviter pour stratégie critique ou validation finale'],
    models: [
      { id: 'llama-3.3-70b-versatile', label: 'Llama 3.3 70B', quality: 'standard', speed: 'fast' },
      { id: 'llama-3.1-8b-instant', label: 'Llama 3.1 8B Instant', quality: 'economy', speed: 'fast' },
    ],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    shortName: 'Replicate',
    category: 'image',
    status: 'planned',
    envVars: ['REPLICATE_API_TOKEN'],
    capabilities: ['image_generation', 'image_editing', 'video_generation'],
    defaultModel: 'black-forest-labs/flux-schnell',
    consoleUrl: 'https://replicate.com/account/api-tokens',
    bestFor: ['Flux', 'modèles open-source', 'tests image alternatifs'],
    limits: ['qualité variable selon modèle', 'latence variable'],
    models: [
      { id: 'black-forest-labs/flux-schnell', label: 'Flux Schnell', quality: 'standard', speed: 'fast', estimatedUnitCost: 0.003 },
    ],
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    shortName: 'Ideogram',
    category: 'image',
    status: 'planned',
    envVars: ['IDEOGRAM_API_KEY'],
    capabilities: ['image_generation'],
    defaultModel: 'ideogram-v3',
    consoleUrl: 'https://ideogram.ai/manage-api',
    bestFor: ['texte dans image', 'affiches', 'slogans visuels'],
    limits: ['à utiliser surtout quand le visuel contient du texte'],
    models: [
      { id: 'ideogram-v3', label: 'Ideogram v3', quality: 'premium', speed: 'medium' },
    ],
  },
  {
    id: 'luma',
    name: 'Luma Dream Machine',
    shortName: 'Luma',
    category: 'video',
    status: 'active',
    envVars: ['LUMA_API_KEY'],
    capabilities: ['video_generation'],
    defaultModel: 'luma-dream-machine',
    consoleUrl: 'https://lumalabs.ai',
    bestFor: ['reels', 'image-to-video', 'animation de visuels Library'],
    limits: ['coût vidéo à surveiller', 'requiert URL image publique'],
    models: [
      { id: 'luma-dream-machine', label: 'Dream Machine', quality: 'premium', speed: 'slow', estimatedUnitCost: 0.35 },
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama local',
    shortName: 'Local',
    category: 'local',
    status: 'planned',
    envVars: ['OLLAMA_BASE_URL'],
    capabilities: ['local_private_task', 'low_cost_draft', 'document_summary'],
    defaultModel: 'llama3.1',
    consoleUrl: 'https://ollama.com',
    bestFor: ['tâches privées', 'drafts gratuits', 'tests hors API payante'],
    limits: ['qualité dépend de la machine locale', 'pas adapté aux décisions premium'],
    models: [
      { id: 'llama3.1', label: 'Llama local', quality: 'economy', speed: 'medium', estimatedUnitCost: 0 },
    ],
  },
]

export function getAIProvider(id: AIProviderId): AIProvider | null {
  return AI_PROVIDERS.find(provider => provider.id === id) ?? null
}

export function getAIProviderStatuses(): AIProviderStatus[] {
  return AI_PROVIDERS.map(provider => {
    const missingEnvVars = provider.envVars.filter(key => !process.env[key])
    return {
      ...provider,
      configured: missingEnvVars.length === 0,
      missingEnvVars,
    }
  })
}
